### ISSUE TITLE
Bare and Standard repositories returns two repositories outputs, the remote one and the local one.

### ISSUE THREAD

**Issue by bzz** [src-d/engine#254] opened 2017-12-11 16:01 UTC
As a user, when running Engine over 1 local git repository `engine.getRepositories.count == 2`.

Steps to reproduce:
```
mkdir test-repo-root
cd test-repo-root; git clone git@github.com:bblfsh/client-scala.git; cd -

"${SPARK_HOME}"/bin/spark-shell --packages "tech.sourced:engine:0.1.12"
```

And then

```
import tech.sourced.engine._
val engine = Engine(spark, "./test-repo-root/")
engine.getRepositories.count
```

It might be a correct behaviour that is worth documenting or a missing feature or a bug.

**Comment by erizocosmico** [comment] 2017-12-11 16:05
This is actually the intended behavior.

Rationale behind this:

Imagine you have a repository with two remotes `foo` and `bar`. You run `git checkout -b baz`.
What remote does `baz` belong to? The answer is none of them. Therefore, there must be a catchall repository for every single git repository which is the local git repository, represented by the path to the repository itself.

While I agree this may be confusing is absolutely needed for correctness, if correctness is what we value.

**Comment by erizocosmico** [comment] 2018-01-05 09:34
Now you can filter using `is_remote = true` to skip all local references. Shall we close this, then, as this is the intended behavior?

**Comment by erizocosmico** [comment] 2018-01-15 15:56
Now there is a `getRemoteReferences` to not even have to filter manually. Closing this. Please, reopen if you find that you still need changes on our side.

**Closed by erizocosmico** 2018-01-15 15:56 UTC
Labels: functionality-discussion
