### ISSUE TITLE
engine not compatible with Apache Spark 2.3.0

### ISSUE THREAD

**Issue by smola** [src-d/engine#343] opened 2018-03-21 09:00 UTC
## Expected Behavior

With Apache Spark 2.3.0:

```
scala> engine.getRepositories.filter('id === "github.com/mawag/faq-xiyoulinux").show
# ... whatever ...
```

## Current Behavior

```
scala> engine.getRepositories.filter('id === "github.com/mawag/faq-xiyoulinux").show
java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.LogicalRelation.<init>(Lorg/apache/spark/sql/sources/BaseRelation;Lscala/collection/Seq;Lscala/Option;)V
  at tech.sourced.engine.rule.AddSourceToAttributes$.tech$sourced$engine$rule$AddSourceToAttributes$$withMetadata(AddSourceToAttributes.scala:43)
  at tech.sourced.engine.rule.AddSourceToAttributes$$anonfun$apply$1.applyOrElse(AddSourceToAttributes.scala:25)
  at tech.sourced.engine.rule.AddSourceToAttributes$$anonfun$apply$1.applyOrElse(AddSourceToAttributes.scala:23)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:289)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:289)
  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:288)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:306)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:304)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:286)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:306)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:304)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:286)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:306)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:304)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:286)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:306)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:304)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:286)
  at tech.sourced.engine.rule.AddSourceToAttributes$.apply(AddSourceToAttributes.scala:23)
  at tech.sourced.engine.rule.AddSourceToAttributes$.apply(AddSourceToAttributes.scala:15)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:87)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:84)
  at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
  at scala.collection.immutable.List.foldLeft(List.scala:84)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:84)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:76)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:76)
  at org.apache.spark.sql.execution.QueryExecution.optimizedPlan$lzycompute(QueryExecution.scala:66)
  at org.apache.spark.sql.execution.QueryExecution.optimizedPlan(QueryExecution.scala:66)
  at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:72)
  at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:68)
  at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:77)
  at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:77)
  at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3248)
  at org.apache.spark.sql.Dataset.head(Dataset.scala:2484)
  at org.apache.spark.sql.Dataset.take(Dataset.scala:2698)
  at org.apache.spark.sql.Dataset.showString(Dataset.scala:254)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:723)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:682)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:691)
  ... 51 elided
```

## Possible Solution
* We probably need to make it compatible with the new internal API.
* Or change the README.md to add a compatibility version table of engine versions and Apache Spark versions, instead of just recommending `>=2.2.0`.

## Steps to Reproduce (for bugs)
See above.

## Context
I just tried latest Apache Spark version the first time instad of `2.2.0` or `2.2.1`. I have no particular reason to use `2.3.0` yet.

## Your Environment (for bugs)
* Version used: 0.5.4
* Operating System and version: Ubuntu Linux Xenial
* Some needed resources to reproduce the problem: Apache Spark 2.3.0 (hadoop 2.7 included)

**Comment by ajnavarro** [comment] 2018-03-27 08:38
@smola What do you think, just by now, change the readme to say that engine is compatible only with 2.2.x?

I had a look and the problem is they change the `apply` method of `LogicalRelation` to make possible have streaming relations. We are using those methods on our rules to push down Joins, so is impossible keep backward compatibility to `2.2.x` versions.

**Comment by smola** [comment] 2018-03-27 08:42
@ajnavarro Yes, I'd change the README to mark Spark compatibility to 2.2.x. Then create a new version compatible 2.3.x when we decide to upgrade our clusters.

**Comment by ajnavarro** [comment] 2018-03-27 08:49
I already did a PR: https://github.com/src-d/engine/pull/349

**Comment by erizocosmico** [comment] 2018-04-10 08:31
Shall we close this, then?

**Comment by erizocosmico** [comment] 2018-04-23 08:52
ping @ajnavarro @smola

**Comment by ajnavarro** [comment] 2018-04-23 14:14
I think so. Maybe in the future we can open a new issue if we want to move to spark 2.3.0. What do you think @smola ?

**Comment by smola** [comment] 2018-04-23 17:04
@ajnavarro It's your call ;-)

**Comment by ajnavarro** [comment] 2018-04-24 07:39
closing then, because the original bug is resolved.

**Closed by ajnavarro** 2018-04-24 07:39 UTC
Labels: bug
