### ISSUE TITLE
`kill` nukes the docker registry

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/engine#61] opened 2018-09-26 06:24 UTC
I run `srcd kill` and this is what it does:

```
INFO[0000] removing containers...                       
INFO[0000] removing container srcd-cli-gitbase          
INFO[0000] removing container srcd-cli-pilosa           
INFO[0001] removing container srcd-cli-bblfshd          
INFO[0002] removing container srcd-cli-daemon           
INFO[0003] removing volumes...                          
INFO[0003] removing volume srcd-cli-bblfsh-storage      
INFO[0006] removing images...                           
INFO[0006] removing image srcd/gitbase:latest           
INFO[0006] removing image bblfsh/bblfshd:latest         
INFO[0007] removing image srcd/style-analyzer:latest    
INFO[0007] removing image srcd/cli-daemon:latest        
INFO[0007] removing image srcd/gitbase-web:latest       
INFO[0007] removing image srcd/spark:2.2.1              
INFO[0007] removing image srcd/codelab:latest           
INFO[0009] removing image pilosa/pilosa:v0.9.0          
INFO[0009] removing image srcd/spark:2.2.0_v2
```

Removing containers is fine, but removing images o_O It erases bblfshd which I use frequently, spark (btw: two versions??) and style-analyzer which is innocent.

My suggestion is to not remove the images by default - it is very cruel.

**Comment by marnovo** [comment] 2018-09-26 08:30
Maybe to remove images something along the lines of the `prune` command you see in things like Homebrew?

**Comment by campoy** [comment] 2018-10-11 23:40
Yes, this should be fixed.

Who's the current maintainer of this, @mcuadros ?

**Comment by vmarkovtsev** [comment] 2018-10-12 08:29
Máximo wrote me in DM that Applications are responsible.

**Closed** 2018-10-23 14:28 UTC

**Comment by bzz** [comment] 2018-10-24 16:31
> Hey @bzz, it seems you're responsible for this issue.

thanks for heads up @campoy and a quick fix @smacker !

I belive both are true since the beginning of the 2018Q4: 
 - App team maintains engine
 - I'm on LA team :)

**Comment by smacker** [comment] 2018-10-25 08:55
which request? the issue is fixed already
