### ISSUE TITLE
java.io.InvalidClassException: tech.sourced.engine.util.EqualFilter; no valid constructor

### ISSUE THREAD

**Issue by zurk** [src-d/engine#339] opened 2018-03-06 14:43 UTC
## Expected Behavior
Engine should be able to analyze PGA and extract UAST from source code.

## Current Behavior
It fails with exception on worker:
```
18/03/06 14:20:53 ERROR Utils: Exception encountered
java.io.InvalidClassException: tech.sourced.engine.util.EqualFilter; no valid constructor
	at java.io.ObjectStreamClass$ExceptionInfo.newInvalidClassException(ObjectStreamClass.java:150)
	at java.io.ObjectStreamClass.checkDeserialize(ObjectStreamClass.java:790)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1782)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at scala.collection.immutable.List$SerializationProxy.readObject(List.scala:479)
	at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1909)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
	at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$8.apply(TorrentBroadcast.scala:293)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1337)
	at org.apache.spark.broadcast.TorrentBroadcast$.unBlockifyObject(TorrentBroadcast.scala:294)
	at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$readBroadcastBlock$1.apply(TorrentBroadcast.scala:226)
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1303)
	at org.apache.spark.broadcast.TorrentBroadcast.readBroadcastBlock(TorrentBroadcast.scala:206)
	at org.apache.spark.broadcast.TorrentBroadcast._value$lzycompute(TorrentBroadcast.scala:66)
	at org.apache.spark.broadcast.TorrentBroadcast._value(TorrentBroadcast.scala:66)
	at org.apache.spark.broadcast.TorrentBroadcast.getValue(TorrentBroadcast.scala:96)
	at org.apache.spark.broadcast.Broadcast.value(Broadcast.scala:70)
	at tech.sourced.engine.GitRelation$$anonfun$buildScan$1$$anonfun$apply$2.apply(DefaultSource.scala:103)
	at tech.sourced.engine.GitRelation$$anonfun$buildScan$1$$anonfun$apply$2.apply(DefaultSource.scala:97)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at tech.sourced.engine.GitRelation$$anonfun$buildScan$1.apply(DefaultSource.scala:97)
	at tech.sourced.engine.GitRelation$$anonfun$buildScan$1.apply(DefaultSource.scala:87)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:395)
	at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$1$$anon$1.hasNext(InMemoryRelation.scala:133)
	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:215)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1038)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1029)
	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:969)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1029)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:760)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:334)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:285)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

## Steps to Reproduce (for bugs)
go to our cluster: 
```
kubectl run -i --tty spark-$USER --image=srcd/spark:2.2.0_v2 --generator="run-pod/v1" --command -- /bin/bash
```
run
``` bash
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py
pip install pyspark==2.2.0.post0 sourced-engine
python -m zipfile -c sourced-engine.zip /usr/local/lib/python2.7/dist-packages/sourced/
```
execute (code from Engine example: https://github.com/src-d/engine/blob/master/examples/notebooks/Example.ipynb)
```python
from sourced.engine import Engine
from pyspark.sql.functions import *
engine = Engine(spark, "hdfs://hdfs-namenode:8020/apps/borges/1k", "siva")
head_blobs = engine.repositories.filter("is_fork = false")\
	.references.filter("is_remote = true")\
	.head_ref.commits\
	.tree_entries.blobs\
	.classify_languages()\
	.filter("is_binary = false")\
	.filter(col("lang").isin(["Python", "Java"]))\
	.sample(False, 0.05, 1024)\
	.extract_uasts()\
	.cache()
c = head_blobs.count()
```
It fails quikly.

## Context
Trying to collect identifier data.

## Your Environment (for bugs)
Version used: 0.5.2
Src-d staging cluster

**Comment by zurk** [comment] 2018-03-06 14:48
Same for 
```python
engine.repositories\
.references.filter("is_remote = true")\
.select("repository_id")\
.distinct()\
.show(10, False)
```

**Comment by r0mainK** [comment] 2018-03-09 14:06
Got the same error, was able to get rid of it by uninstalling engine, cloning the engine repo and doing `cp Filters.scala EqualFilter.scala`  in `engine/src/main/scala/tech/sourced/engine/util/` before reinstalling it with `pip3 install .` in `engine/python`

I guess the engine thinks that the `EqualFilter` class, which is in the `Filters.scala` file, has its own file.

**Comment by zurk** [comment] 2018-03-12 09:39
@r0mainK thank you for a workaround!
Can you add exact commands you run?

**Comment by r0mainK** [comment] 2018-03-12 09:43
@zurk no problem, sure instead of installing engine do:
```
cd /home
git clone https://github.com/src-d/engine
cd /home/engine/src/main/scala/tech/sourced/engine/util/
cp Filters.scala EqualFilter.scala
cd /home/engine/python
pip3 install .
```
After that it should work (it did for me)

**Comment by vmarkovtsev** [comment] 2018-03-13 09:20
@antonio Although we have the workaround now, would still be nice to see this addressed :)

**Comment by ajnavarro** [comment] 2018-03-13 10:09
@vmarkovtsev Not reproducible using the last version of our docker container:

Run bblfshd:
`docker run -d --name bblfshd --privileged -p 9432:9432 -v /var/lib/bblfshd:/var/lib/bblfshd bblfsh/bblfshd`

Run engine:
`docker run --name engine-jupyter --rm -it -p 8080:8080 -v /path/to/repositories/:/repositories srcd/engine-jupyter:v0.5.2`

Execute queries:

`head_blobs = engine.repositories.filter("is_fork = false")\
	.references.filter("is_remote = true")\
	.head_ref.commits\
	.tree_entries.blobs\
	.classify_languages()\
	.filter("is_binary = false")\
	.filter(col("lang").isin(["Python", "Java"]))\
	.sample(False, 0.05, 1024)\
	.extract_uasts()\
	.cache()
head_blobs.count()`

On the other hand, If `engine.repositories.show()` is failing with the same error as the previous complex query, something is wrong with the environment where engine is being executed. I bet the problem is that you have two versions of the engine on the classpath.

**Comment by r0mainK** [comment] 2018-03-13 11:00
The solution I proposed doesn't seem to be working now, tried it out now on the new pods (engine is now pre-installed) and it failed. In retrospect I don't know why it worked the first time, since the scala files are probably only stored in the jar.  

However I think the problem is actually what @ajnavarro said: 
- when I tried to run the 3 test scripts in with the spark cluster deployed on `local-gpu` I got the same results he did, only the `.show()` worked.
- when i tried with the local spark, with this command: `pyspark  -c 'spark.local.dir=/spark-temp-data' --total-executor-cores 32 --driver-memory 16g --executor-memory 4g  --packages "tech.sourced:engine:0.5.2"` the 2nd script worked, and the third failed for another reason (not using the same hdfs repo, not all file were commits)

**Comment by r0mainK** [comment] 2018-03-13 15:52
Don't know if it helps given I know little about Scala but this error seems to be documented: 
- https://groups.google.com/forum/#!topic/akka-user/3Q_qid0NnjU
- https://stackoverflow.com/questions/9747443/java-io-invalidclassexception-no-valid-constructor
- https://stackoverflow.com/questions/17153686/no-valid-constructor-during-serialization/17154055 

The error logs on these issues are quite similar, and given the bug doesn't seem to happen when using the local spark, on a k8 pod or docker containers, it might be the serialization process of the Filter subclasses  when using the spark cluster that is causing this bug.

**Comment by r0mainK** [comment] 2018-03-13 18:20
Btw @ajnavarro I found in the logs of the spark worker the classpath, didn't see two instances of the engine. I also tried to add jar dependencies in that folder for each worker, but it did nothing. Do you have any other ideas of what could be wrong ?

**Comment by r0mainK** [comment] 2018-03-14 15:15
UPDATE:

## Steps to Reproduce (for bugs)

- download and unpack spark 2.2.1 from https://spark.apache.org/downloads.html
- Clone the engine to get example siva files `git clone https://github.com/src-d/engine.git`
- start master: go in the spark folder then run `./sbin/start-master.sh`
- check web UI http://127.0.0.1:8080 to get the master spark url (e.g.:  `spark://Romains-MacBook-Pro.local:7077` )
- start a worker ./sbin/start-slave.sh <master-spark-URL> then check on the UI it's up
- start shell: `pyspark --master <master-spark-URL> --packages "tech.sourced:engine:0.5.2" --total-executor-cores 32 --driver-memory 16g --executor-memory 4g`
- Run these commands on the example siva files in the engine repo:
```
from sourced.engine import Engine
from pyspark.sql.functions import * 
engine = Engine(spark, '/Users/romain/src-d/engine/examples/siva-files/', 'siva')
engine.repositories.show()  # should work
engine.repositories.references.filter("is_remote = true").select("repository_id").show() # should fail
```

**Comment by bzz** [comment] 2018-03-14 15:51
The problem seems to happen only on a cluster deployment mode i.e Spark Standalone.

The reason seems to be that [EqualFilter](https://github.com/src-d/engine/blob/master/src/main/scala/tech/sourced/engine/util/Filters.scala#L195) is [broadcasted](https://github.com/src-d/engine/blob/master/src/main/scala/tech/sourced/engine/MetadataSource.scala#L92) to executors, but according to [SI-4278](https://issues.scala-lang.org/browse/SI-4278) intentionally not serializable by default.

If the assessment above is current, a fix should be rather simple, so going submit a PR soon.

**Comment by ajnavarro** [comment] 2018-03-15 08:44
Good work @bzz , thanks a lot!

**Comment by bzz** [comment] 2018-03-20 05:05
Taking a liberty of closing this guy, as soon as https://github.com/src-d/engine/releases/tag/v0.5.3 has been release and includes the fix.

Thanks everyone for helping to fix this, ✨ team ✨ !

But please, feel free to re-open it in case this is not fully resolved yet.

**Closed by bzz** 2018-03-20 05:05 UTC
Labels: bug
