### ISSUE TITLE
Repository on a siva file keeps returning rows indefinitely.

### ISSUE THREAD

**Issue by EgorBu** [src-d/engine#246] opened 2017-12-05 17:03 UTC
Hi,
I found `siva` that is very suspicious. It looks like that it `engine` goes into infinite loop somehow with this `siva` file.
What I do - pipeline description:

1) Create engine with this specific `siva` file
2) Select top 3 commits
3) Deduplicate based on `blob_id`
4) Filter by `is_binary=false`
5) Extract UAST
6) Select only specific fields
7) Save to parquet

But this pipeline never finishes.

```
Scan GitRelation(org.apache.spark.sql.SparkSession@18c1619a,StructType(StructField(blob_id,StringType,false), bla bla(details below)
number of output rows: 46,841,601

Filter number of output rows: 20,547
```

And a number of rows after filter stays the same when a number of rows after scan grows from several dozen thousand to 46M (some of the experiments showed even more than 300M when I was patient).
And this process never finishes.

Can you help me to figure out what's wrong?

[siva file](https://drive.google.com/a/sourced.tech/file/d/13YTnjZZJfP52nJehAl-r5yrEcNBILXYm/view?usp=sharing)

<details>

```
Scan GitRelation(org.apache.spark.sql.SparkSession@18c1619a,StructType(StructField(blob_id,StringType,false), StructField(commit_hash,StringType,false), StructField(repository_id,StringType,false), StructField(reference_name,StringType,false), StructField(content,BinaryType,true), StructField(is_binary,BooleanType,false), StructField(commit_hash,StringType,false), StructField(repository_id,StringType,false), StructField(reference_name,StringType,false), StructField(path,StringType,false), StructField(blob,StringType,false), StructField(repository_id,StringType,false), StructField(reference_name,StringType,false), StructField(index,IntegerType,false), StructField(hash,StringType,false), StructField(message,StringType,false), StructField(parents,ArrayType(StringType,false),true), StructField(parents_count,IntegerType,false), StructField(author_email,StringType,true), StructField(author_name,StringType,true), StructField(author_date,TimestampType,true), StructField(committer_email,StringType,true), StructField(committer_name,StringType,true), StructField(committer_date,TimestampType,true), StructField(repository_id,StringType,false), StructField(name,StringType,false), StructField(hash,StringType,false), StructField(id,StringType,false), StructField(urls,ArrayType(StringType,false),false), StructField(is_fork,BooleanType,true)),Some(((blob#152 = blob_id#190) && ((commit_hash#148 = hash#43) && (((repository_id#9 = repository_id#40) && (reference_name#41 = name#10)) && (repository_id#9 = id#0))))),None)  number of output rows: 46,841,601

Filter number of output rows: 20,547

Sort sort time total (min, med, max): 0 ms (0 ms, 0 ms, 0 ms)peak memory total (min, med, max): 0.0 B (0.0 B, 0.0 B, 0.0 B)spill size total (min, med, max): 0.0 B (0.0 B, 0.0 B, 0.0 B)
```
</details>

**Comment by ajnavarro** [comment] 2017-12-07 09:37
I can guess for your columns names that you are using engine v0.2.0, right?

**Comment by ajnavarro** [comment] 2017-12-07 09:41
> Select top 3 commits

Can I guess top 3 commits for each branch? or just from HEAD?

**Comment by ajnavarro** [comment] 2017-12-07 10:33
I can reproduce the error if I don't filter references:

`engine.getRepositories.getReferences.getCommits.count()`

**Comment by EgorBu** [comment] 2017-12-07 10:50
* yes, engine has v0.2.0
* here it's how files are selected - references are not filtered:
```python
    def __call__(self, engine):
        commits = engine.repositories.references.head_ref.commits
        if self.dzhigurda == -1:
            # Use all available commits
            chosen = commits
        else:
            chosen = commits.filter(commits.index <= self.dzhigurda)
        return chosen.tree_entries.blobs
```

**Comment by ajnavarro** [comment] 2017-12-07 11:14
It's not iterating forever, there are just a lot of references and commits to iterate. Because of no filters are used at reference level, 6374 references will be iterated (including release tags, pull request not merged and merged, and of course "standard" branches).

The result of `engine.getRepositories.getReferences.getCommits.count()` is `44662573` and it takes about 30 min to finish.

Depending of your use case, you should filter by reference name (because it's optimized at datasource level).

**Closed** 2017-12-07 11:15 UTC
Labels: bug
