### ISSUE TITLE
Engine fails on siva files from pipeline-staging cluster

### ISSUE THREAD

**Issue by fulaphex** [src-d/engine#414] opened 2018-07-10 21:16 UTC
## Expected Behavior
Skip the siva file and continue processing.

## Current Behavior
I'm getting this error while processing `hdfs://hdfs-namenode/pga/siva/latest/55` on `pipeline-staging` cluster:
```
tech.sourced.siva.SivaException: Exception at file 5559a23b77e8cbf94961deaa3c3473ad3734fbe1.siva: At Index footer, index size: Java implementation of siva doesn't support values greater than 9223372036854775807
```

## Steps to Reproduce (for bugs)
1. Deploy a pod on pipeline-staging cluster with `srcd/engine-jupyter:v0.7.0` image.
2. Modify first cell to change the repositories location and run:
```
from sourced.engine import Engine
from pyspark.sql import SparkSession
from pyspark.sql.functions import *

spark = SparkSession.builder\
.master("local[*]").appName("Examples")\
.getOrCreate()

engine = Engine(spark, "hdfs://hdfs-namenode/pga/siva/latest/55", "siva")

print("%d repositories successfully loaded" % (engine.repositories.count()/2))
```
I left the pod `gabor-engine-jupyter` with the modified `Example.ipynb` and saved the failed run.
Copy of the logs is also [here](https://gist.github.com/fulaphex/541d3fcb201e335896af73a83468877f).

## Context
I'm processing siva files on `pipeline-staging` and gathering stats to compare pga versions between clusters.

**Comment by ajnavarro** [comment] 2018-07-11 07:31
You can skip siva read errors: https://github.com/src-d/engine/blob/master/python/sourced/engine/engine.py#L30

Just change
```python
engine = Engine(spark, "hdfs://hdfs-namenode/pga/siva/latest/55", "siva")
```
to
```python
engine = Engine(spark, "hdfs://hdfs-namenode/pga/siva/latest/55", "siva",False,True)
```

**Comment by fulaphex** [comment] 2018-07-11 08:34
When I encountered the error I was using this option and it still fails in the same way with:
```
from sourced.engine import Engine
from pyspark.sql import SparkSession
from pyspark.sql.functions import *

spark = SparkSession.builder\
.master("local[*]").appName("Examples")\
.getOrCreate()

engine = Engine(spark, "hdfs://hdfs-namenode/pga/siva/latest/55", "siva", False, True)

print("%d repositories successfully loaded" % (engine.repositories.count()/2))
```
Updated [logs](https://gist.github.com/fulaphex/541d3fcb201e335896af73a83468877f).

**Comment by erizocosmico** [comment] 2018-07-11 15:01
This must be a siva-java issue, go-siva unpacks it just fine.

**Comment by fulaphex** [comment] 2018-07-11 17:21
@erizocosmico I downloaded all siva files starting with 55 with pga tool and it works fine. The problem seems to be with the files on the hdfs on the pipeline-staging cluster.

btw: I also encountered this:
```
tech.sourced.siva.SivaException: Exception at file 9b1a3c1efc7e3c9ee0625159b909e6e7f98d2963.siva: Error reading index of file.
```

**Comment by erizocosmico** [comment] 2018-07-12 08:12
You mean if you download the file locally the engine works just fine with it?

**Comment by erizocosmico** [comment] 2018-07-12 08:28
Turns out opening the file with siva java does not fail either, so the problem is not there

**Comment by fulaphex** [comment] 2018-07-12 09:31
Yes, when I download the single file it works fine. 
I also tried recreating same scenario with files downloaded with [pga tool](https://github.com/src-d/datasets/tree/master/PublicGitArchive/pga) and it also works fine. 
It only crashes when I run on cluster reading files from hdfs, although I don't know if the files on hdfs are the same ones that pga tool downloads.

**Comment by erizocosmico** [comment] 2018-07-12 10:11
You gave me an idea. I downloaded the same siva file, this time from HDFS instead of `pga`. `go-siva` and `siva-java` cannot read it now. So the problem is the files are corrupted in HDFS.

@ajnavarro what should we do about that?

**Comment by erizocosmico** [comment] 2018-07-12 10:20
@fulaphex whoever did the copy of the original siva files to that folder you're using did it wrong or some files were corrupted during that copy, because the siva file there is corrupted, but the original (in `/apps/borges/root-repositories/`) is not.

You can either use `/apps/borges/root-repositories/` or try to do the copy again

**Comment by bzz** [comment] 2018-07-17 17:17
@erizocosmico @ajnavarro this is indeed the case of .siva file beeing corrupted

> whoever did the copy of the original siva files to that folder you're using did it wrong

Although this suggestion does not look very constructive, this most probably happened on `pga get`, before it get md5 verification on download https://github.com/src-d/datasets/pull/69 (which BTW is still not merged yet, so this means ALL `pga` clients have chance of having this)

You guys did a great job introducing option for not breaking Engine on reading corrupted siva files in https://github.com/src-d/engine/pull/395 but it only covers things, reachable with iterators.

Right now, we can see Engine canceling the job on read error in a different place, in [RepositoryProvider.genSivaRepository](https://github.com/src-d/engine/blob/4ac72dbdb06c286d44321889fff84c1516df0df2/src/main/scala/tech/sourced/engine/provider/RepositoryProvider.scala#L251).

What do you think if with the same configuration option we allow RepositoryProvider to also skip .siva files (ideally with some metric counter)?

This way, it can be treated as part of original https://github.com/src-d/engine/issues/393

**Comment by ajnavarro** [comment] 2018-07-18 07:29
We cannot expect engine working correctly if the files themselves are not even readable. If some parquet file is corrupted, what do you expect that spark will do? continue? or fail?

The bug here is in the tool or process used to download siva files in my opinion.

**Comment by bzz** [comment] 2018-07-18 08:00
I see! I'm not saying it's a bug in Engine - engine works and siva files are corrupted for sure. 

Rather I'm saying that as a user, I would love to have an option not to fail the whole job on such files, and am asking if you would be open to extend `spark.tech.sourced.engine.skip.read.errors=true` behaviour to avoid this failure mode as well.

If that case, we could close this in favor of https://github.com/src-d/engine/issues/393 (or a new similar feature request) and then I would be happy to look deeper into this and submit a patch. WDYT?

**Comment by smola** [comment] 2018-07-18 10:59
`spark.tech.sourced.engine.skip.read.errors` was a compromise solution that we agreed on because final PGA release contains some repository with missing objects. We just needed to work with our own released dataset.

On the other hand, if we have further corruption in one of our downloaded copies, I do not see much value in us working with that corrupted copy. I would rather direct our efforts at [fixing pga tool](https://github.com/src-d/datasets/pull/69) as well as ensuring that we have a proper copy in our cluster.

@fulaphex In the mean time, you can try with the PGA copy at `/pga2` directory, which was a second download with improved pga tool.

**Closed** 2018-07-18 12:32 UTC
Labels: wontfix

**Comment by fulaphex** [comment] 2018-07-26 10:39
@smola `/pga2` works better, I was able to process everything there.
