### ISSUE TITLE
Gitbase - "query failed: connection refused"

### ISSUE THREAD

**Issue by gomesfernanda** [src-d/engine#50] opened 2018-08-29 14:02 UTC
I'm trying to use the interface of gitbase, after installing the engine according to ["quickstart" on documentation](https://docs.sourced.tech/engine/#quickstart).

After getting an error, I tried cleaning up and restarting it. I followed the commands below and got the error on the image that's attached.

```
$ srcd kill
INFO[0000] removing containers...
INFO[0000] removing container srcd-cli-bblfshd
INFO[0000] removing container srcd-cli-daemon
INFO[0001] removing volumes...
INFO[0001] removing volume srcd-cli-bblfsh-storage
INFO[0002] removing images...
INFO[0002] removing image srcd/cli-daemon:latest
INFO[0002] removing image bblfsh/bblfshd:latest


$ srcd init
INFO[0000] starting daemon with working directory: /Users/fernandagomes
INFO[0000] installing "srcd/cli-daemon:latest"
INFO[0004] installed "srcd/cli-daemon:latest"


$ srcd web sql
INFO[0003] this is taking a while, if this is the first time you launch this web client, it might take a few more minutes while we install all the required images
Go to http://localhost:8080 for the gitbase web client. Press Ctrl-C to stop it.
```

![image](https://user-images.githubusercontent.com/21245928/44792728-d61cd480-aba4-11e8-90e5-7b366aebd24e.png)

**Comment by eiso** [comment] 2018-08-29 14:28
@gomesfernanda can you run `docker ps -a` and paste the output here.

**Comment by gomesfernanda** [comment] 2018-08-29 15:07
When running `docker ps -a` I get:


|CONTAINER ID|IMAGE|COMMAND|CREATED|STATUS|PORTS|NAMES|
|---|---|---|---|---|---|---|
|089c1f7bfde5|srcd/gitbase-web|"/bin/gitbase-web"|40 seconds ago|Up 39 seconds|0.0.0.0:8080->8080/tcp|srcd-cli-gitbase-web|
|5a08dbfa8ebd|srcd/gitbase|"/tini -- /bin/sh -c…"|About a minute ago|Up About a minute|0.0.0.0:3306->3306/tcp|srcd-cli-gitbase|
|515382492cfc|pilosa/pilosa:v0.9.0|"/pilosa server --da…"|4 minutes ago|Up 4 minutes|10101/tcp|srcd-cli-pilosa|
|02bce490ac49|bblfsh/bblfshd|"bblfshd -ctl-addres…"|6 minutes ago|Up 6 minutes|0.0.0.0:9432->9432/tcp|srcd-cli-bblfshd|
|39c5949a38f4|srcd/cli-daemon|"/srcd-server --work…"|6 minutes ago|Up 6 minutes|0.0.0.0:4242->4242/tcp|srcd-cli-daemon|
|40a5dd23deab|7379a3cad7ac|"bblfshd"|8 minutes ago|Exited (255) 3 days ago|0.0.0.0:9432->9432/tcp|bblfshd|

**Comment by smacker** [comment] 2018-11-06 11:30
Please try with v0.2.0, it produces better logs. I'm closing for now because I can't reproduce the issue.
But feel free to reopen it if you still have the problem with the newer version.

**Closed by smacker** 2018-11-06 11:30 UTC
