### ISSUE TITLE
error while marshaling: proto: invalid UTF-8 string

### ISSUE THREAD

**Issue by willis7** [src-d/engine#196] opened 2019-01-27 20:06 UTC
I am following the intro tut on my local repos and hit this error when calling the following:

Retrieve the UAST for all files from HEAD:
```sql
SELECT * FROM (
    SELECT cf.file_path,
           UAST(f.blob_content, LANGUAGE(f.file_path,  f.blob_content)) as uast
    FROM ref_commits r 
    NATURAL JOIN commit_files cf 
    NATURAL JOIN files f 
    WHERE r.ref_name = 'HEAD' 
    AND r.history_index = 0
) t WHERE uast != '';
```

The full error is

`rpc error: code = Internal desc = grpc: error while marshaling: proto: invalid UTF-8 string`

The error simply doesn't give enough information to provide anything further to assist this ticket.

**Comment by carlosms** [comment] 2019-01-28 10:09
Thank you for reporting this. I can reproduce it with engine v0.8.0, which includes gitbase v0.18.0.

The query works if it is run from gitbase-web (`srcd web sql`), or a mysql client (`mysql -q -u root -h  127.0.0.1 gitbase`).

**Comment by carlosms** [comment] 2019-01-28 10:13
Another comment. Even if it worked, we should say in the docs that this query only makes sense from the web UI. From the cli the UAST column is just a binary gibberish you can't read.

**Comment by se7entyse7en** [comment] 2019-02-05 19:42
@carlosms this seems to be already known on [bblfshd](https://github.com/bblfsh/bblfshd/issues/2380), what do we do in this case? Are we going to close this one?

**Comment by carlosms** [comment] 2019-02-06 11:49
> @carlosms this seems to be already known on [bblfshd](https://github.com/bblfsh/bblfshd/issues/2380), what do we do in this case? Are we going to close this one? Or we're going to close this as soon as it is closed on bblfshd side?

Wrong link, should be https://github.com/bblfsh/bblfshd/issues/238.

I think this issue and the bblfsh issue are not related. They might have the same root cause, but the fix for https://github.com/bblfsh/bblfshd/issues/238 will not solve the issue in engine.

I could reproduce the problem with valid UAST contents, so I think the problem is in the communication between the `srcd sql` protobuf client and our server.

**Comment by carlosms** [comment] 2019-02-06 11:50
About the hanging containers, I have no clues as to what can be happening. Please confirm if it is something you can reproduce, and try to debug it further.

**Comment by creachadair** [comment] 2019-02-07 00:50
> I think the problem is in the communication between the `srcd sql` protobuf client and our server.

I believe that's correct. Specifically, I believe the likely cause is trying to put non-text content into a protobuf field of type `string`. I assumed in debugging bblfsh/bblfshd#238 that it was the call to the driver, but given that this mainly (perhaps only) seems to happen via `srcd sql` or similar, I'm guessing it may be elsewhere in the chain. I'm happy to help try things to reproduce it, if you have suggestions for what data you'd find useful.

**Comment by se7entyse7en** [comment] 2019-02-11 10:29
I'm removing my self as assignee for now as I'm not currently actively working on this.

**Comment by se7entyse7en** [comment] 2019-02-11 13:58
@carlosms could you please try this query using `lookout`'s root dir as workdir? How much time does it take for you to execute the query?

**Comment by se7entyse7en** [comment] 2019-02-11 14:09
I'm wondering if this could be related to [this](https://github.com/src-d/engine/issues/156) as this same query works find for smaller repos, but seems to hang/take a lot of time for bigger ones. In particular the `com.docker.hyperkit` process starts using ~200% CPU and ~2GB of res memory.

**Comment by se7entyse7en** [comment] 2019-02-11 14:14
Anyway I've created [another issue](https://github.com/src-d/engine/issues/208) to avoid polluting the discussion here.

**Closed** 2019-02-12 11:18 UTC
Labels: bug
