### ISSUE TITLE
Use `latest-drivers` bblfsh image

### ISSUE THREAD

**Issue by carlosms** [src-d/engine#67] opened 2018-10-09 09:32 UTC
With the current [bblfsh v2.90](https://github.com/bblfsh/bblfshd/releases/tag/v2.9.0) a `bblfshctl driver install` fails for already installed drivers (context [here](https://github.com/bblfsh/bblfshd/issues/195)). 

This means we can get errors like this:
```
$ srcd parse uast ~/repos/gitbase-web/cmd/gitbase-web/main.go 
FATA[0000] could not stream: rpc error: code = AlreadyExists desc = driver already installed: go (image reference: docker://bblfsh/go-driver:latest): %s 
```

We should add the  new `--force` flag to `bblfshctl` (which actually means ignore, not force), or use the new `latest-drivers` images.

**Comment by smacker** [comment] 2018-10-23 16:00
The error mentioned in the issue is fixed here: https://github.com/src-d/engine/pull/84
But we still can consider using `latest-drivers` image.

**Comment by smacker** [comment] 2018-10-25 13:46
I have noticed one problem with `latest-drivers`. This image follows bblfshd release cycle. So it doesn't get updates when bugs are fixed in drivers or even new features are added.

As an example right now the latest drivers image is `v2.9.1-drivers` https://hub.docker.com/r/bblfsh/bblfshd/tags/ released 15 days ago.
But the java-driver is released 20 hours ago https://hub.docker.com/r/bblfsh/java-driver/tags/ 
It is 2 releases newer with changes:
- Fix roles for primitive types
- Support error codes

**Comment by smacker** [comment] 2018-11-19 11:29
In my opinion, we need to discuss it with LA team and agree on some kind of schedule for `-drivers` releases or something like that.

Current release was made 24 days ago, since then in java-driver, for example, was created 3 new releases:
- Enable language namespace in Semantic UAST
- Annotate default function modifier.
- Normalize and annotate Javadoc nodes properly.

We need to incorporate those improvements into engine somehow at some point.

cc @creachadair

**Comment by creachadair** [comment] 2018-11-19 23:00
The above sounds sensible to me. At the very least, it seems like we should have some coordination around which semantic version ranges are compatible with each other. Tightly-coupled releases are hard to maintain, but there should be some middle ground between that and confusing/surprising behaviour for the user.

**Comment by smacker** [comment] 2018-11-20 16:20
here is the change to `-drivers` image: https://github.com/src-d/engine/pull/135

but it still downloads cpp driver separately. Because cpp driver is recommended already but isn't included in latest `drivers` image. (one more example why we need some kind of coordination with LA team)

**Closed** 2018-11-21 11:11 UTC
Labels: empathy-sessions
