### ISSUE TITLE
Exception on every second run in spark-shell

### ISSUE THREAD

**Issue by bzz** [src-d/engine#195] opened 2017-11-16 09:50 UTC
On every _second_ run of the same set of commands in fresh spark-sell and engine 0.1.7, over the same dataset results in exception

```
ava.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at tech.sourced.engine.iterator.RootedRepo$.parseRef(RootedRepoIterator.scala:187)
	at tech.sourced.engine.iterator.CommitIterator.mapColumns(CommitIterator.scala:41)
	at tech.sourced.engine.iterator.CommitIterator.mapColumns(CommitIterator.scala:22)
	at tech.sourced.engine.iterator.RootedRepoIterator.nextRaw(RootedRepoIterator.scala:130)
	at tech.sourced.engine.iterator.RootedRepoIterator.hasNext(RootedRepoIterator.scala:94)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at tech.sourced.engine.iterator.CleanupIterator.hasNext(CleanupIterator.scala:24)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
```

It may has to do with `RootedRerpo.getRepositoryId` returning `Option` and [parseRef]( https://github.com/src-d/engine/blob/dd8de9762c4e022859eb36feef1e39a78bbd628e/src/main/scala/tech/sourced/engine/iterator/RootedRepoIterator.scala#L187) calling `.get`

It might be happening every second time just because of the order of the processing.

Detailed steps to reproduce in https://gist.github.com/bzz/b287b198a61c25b3fd3074ba07273853

**Comment by mcarmonaa** [comment] 2017-11-17 10:45
@bzz what are the lines you are re run from the [code snippet](https://gist.github.com/bzz/b287b198a61c25b3fd3074ba07273853)? I can't reproduce the error

**Comment by mcarmonaa** [comment] 2017-11-21 09:59
Closing issue because following the steps in @bzz [comment](https://github.com/src-d/engine/issues/195#issue-274453971) I couldn't reproduce the exception.

**Closed by mcarmonaa** 2017-11-21 09:59 UTC
